[theme]
base = "dark"
backgroundColor = "#000000"
secondaryBackgroundColor = "#080808"
textColor = "#ffffff"

[client]
# Removes the toolbar menu where visitors can choose a different appearance.
toolbarMode = "minimal"
